config/routes.rb
EmployeeManagement::Application.routes.draw do

  get "holidays/index"

  get "holidays/new"

  get "holidays/edit"

  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration, only: [:edit, :update], path: 'users', controller: 'devise/registrations', as: :user_registration
  end

  root :to => 'dashboard#index'
  resources :roles
  resources :attendances do
    collection do
      get :my_requests
      get :apply_leave
      get :pending_approvals
      get :search_pending_approvals
      get :available_leaves
      get :team_leaves
    end
  end
  post "dashboard/search" => "dashboard#search", :as => :dashboard_search
  resources :dashboard do
    collection do
      get :my_team
      get :approve
      get :entire_team
    end
  end

  resources :users

  resources :holidays

  match ':controller(/:action(:/id))'

  get 'search/search_emails' => 'search#search_emails'
  get 'search/search_name' => 'search#search_name'
  get 'search/search_manager_name' => 'search#search_manager_name'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  respond_to :html, :js
  before_filter :check_manager_or_admin, only: :entire_team

  def index
    @attendance = Attendance.new
  end

  def approve
    @attendance = Attendance.find(params[:approval_id])
    approval_type = params[:commit_action]
    comments = params[:comments]
    if params[:emails_to_notify]
      @attendance.emails_to_notify = params[:emails_to_notify]
      @attendance.save()
    end
    @attendance.process(current_user, approval_type, comments)
    redirect_to pending_approvals_attendances_url
  end

  def search
    start_date = nil
    end_date   = nil
    if !params[:start]['start_date(1i)'].blank?
      start_date = Date.new(params[:start]['start_date(1i)'].to_i, params[:start]['start_date(2i)'].to_i, params[:start]['start_date(3i)'].to_i)
    end
    if !params[:end]['end_date(1i)'].blank?
      end_date = Date.new(params[:end]['end_date(1i)'].to_i, params[:end]['end_date(2i)'].to_i, params[:end]['end_date(3i)'].to_i)
    end

    name = params[:name][0]
    user_id = params[:user_id]
    manager_user_id = params[:manager_user_id]
    pending = params[:pending]
    approved = params[:approved]
    rejected = params[:rejected]
    approval_status_where = ''
    leave = params[:leave]
    wfh = params[:wfh]
    casual = params[:casual]
    sick = params[:sick]
    privilege = params[:privilege]

    if !user_id.blank?
      @user_attendances = Attendance.joins(:user, :leave_type).
          where('users.id=?', user_id)
    elsif !manager_user_id.blank?
      @user_attendances = Attendance.joins(:user, :leave_type).
          where('users.manager_id = ?', manager_user_id)
    else
      if current_user.is_manager? || current_user.is_admin?
        @user_attendances = Attendance.joins(:user, :leave_type).where("user_id IN (?)", current_user.entire_team.collect(&:id))
      else
        @user_attendances = Attendance.joins(:user, :leave_type).joins(:user, :leave_type).
          where('users.manager_id = ?', current_user.id)
      end
    end
    if !start_date.blank?
      @user_attendances = @user_attendances.where('start_date >= ?', start_date)
    end

    if !end_date.blank?
      @user_attendances = @user_attendances.where('end_date <= ?', end_date)
    end
    if !pending.nil?
      approval_status_where = approval_status_where + 'approval_status is NULL'
    end
    if !approved.nil?
      if !approval_status_where.empty?
        approval_status_where = approval_status_where + ' OR approval_status = true'
      else
        approval_status_where = 'approval_status = true'
      end
    end
    if !rejected.nil?
      if !approval_status_where.empty?
        approval_status_where = approval_status_where + ' OR approval_status = false'
      else
        approval_status_where = approval_status_where + 'approval_status = false'
      end
    end

    if !approval_status_where.empty?
      @user_attendances = @user_attendances.where(approval_status_where)
    end

    leave_category_where =''
    if (!leave.nil?)
      leave_category_where = leave_category_where+'is_leave_or_wfh = true'
    end
    if (!wfh.nil?)
      if (!leave_category_where.empty?)
        leave_category_where = leave_category_where+' OR is_leave_or_wfh = false'
      else
        leave_category_where = leave_category_where+'is_leave_or_wfh = false'
      end
    end




    if (!leave_category_where.empty?)
      @user_attendances = @user_attendances.where(leave_category_where)
    end

    leave_type_where=""
    if(!casual.nil?)
      leave_type_where = leave_type_where + " leave_types.name like 'casual' "
    end

    if !sick.nil?
      if !leave_type_where.empty?
        leave_type_where = leave_type_where + " OR leave_types.name like 'sick' "
      else
        leave_type_where = leave_type_where + " leave_types.name like 'sick' "
      end
    end

    if !privilege.nil?
      if !leave_type_where.empty?
        leave_type_where = leave_type_where + " OR leave_types.name like 'privilege' "
      else
        leave_type_where = leave_type_where + " leave_types.name like 'privilege' "
      end
    end

    if (!leave_type_where.empty?)
      @user_attendances = @user_attendances.where(leave_type_where)
    end
    @user_attendances = @user_attendances.paginate(per_page: 10, page: params[:page])

    @sick = Attendance.joins(:user,:leave_type)
                      .where("users.name like ?
                              and leave_types.name like ?
                              and start_date >= ?
                              and end_date <= ?
                              and is_leave_or_wfh = true
                              and approval_status = true",
                              name,'sick',start_date, end_date).sum('attendances.days')

    @casual = Attendance.joins(:user,:leave_type)
                .where("users.name like ?
                              and leave_types.name like ?
                              and start_date >= ?
                              and end_date <= ?
                              and is_leave_or_wfh = true
                              and approval_status = true",
                       name,'casual',start_date, end_date).sum('attendances.days')

    @privilege = Attendance.joins(:user,:leave_type)
                .where("users.name like ?
                              and leave_types.name like ?
                              and start_date >= ?
                              and end_date <= ?
                              and is_leave_or_wfh = true
                              and approval_status = true",
                       name,'privilege',start_date, end_date).sum('attendances.days')
    @name = name

  end

  def search_my_requests
    start_date = Date.new(params[:start]['start_date(1i)'].to_i,
                          params[:start]['start_date(2i)'].to_i,
                          params[:start]['start_date(3i)'].to_i)
    end_date = Date.new(params[:end]['end_date(1i)'].to_i,
                        params[:end]['end_date(2i)'].to_i,
                        params[:end]['end_date(3i)'].to_i)

    pending = params[:pending]
    approved = params[:approved]
    rejected = params[:rejected]
    approval_status_where = ''
    leave = params[:leave]
    wfh = params[:wfh]

    @user_attendances = Attendance.joins(:user).
        where('users.id = ?', current_user.id)

    if !start_date.nil?
      @user_attendances = @user_attendances.where('start_date >= ?', start_date)
    end

    if (!end_date.nil?)
      @user_attendances = @user_attendances.where('end_date <= ?', end_date)
    end
    if (!pending.nil?)
      approval_status_where = approval_status_where + 'approval_status is NULL'
    end
    if !approved.nil?
      if !approval_status_where.empty?
        approval_status_where = approval_status_where + ' OR approval_status = true'
      else
        approval_status_where = approval_status_where + 'approval_status = true'
      end
    end
    if !rejected.nil?
      if !approval_status_where.empty?
        approval_status_where = approval_status_where + ' OR approval_status = false'
      else
        approval_status_where = approval_status_where + 'approval_status = false'
      end
    end

    if !approval_status_where.empty?
      @user_attendances = @user_attendances.where(approval_status_where)
    end

    leave_type_where =''
    if (!leave.nil?)
      leave_type_where = leave_type_where+'is_leave_or_wfh = true'
    end
    if (!wfh.nil?)
      if (!leave_type_where.empty?)
        leave_type_where = leave_type_where+' OR is_leave_or_wfh = false'
      else
        leave_type_where = leave_type_where+'is_leave_or_wfh = false'
      end
    end

    if (!leave_type_where.empty?)
      @user_attendances = @user_attendances.where(leave_type_where)
    end

    respond_to do |format|
      format.js { render :template => "dashboard/search_my_requests" }
    end

  end

  def my_team
    @my_team = current_user.team_members.paginate(page: params[:page], per_page: 20).order(:name)
  end

  def entire_team
    @entire_team = current_user.entire_team.paginate(:page => params[:page], :per_page => 20)
  end

  private

  def check_manager_or_admin
    redirect_to root_path if (!current_user.is_manager? && !current_user.is_admin?)
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_attendance_show.html.erb
<%= will_paginate attendances, renderer: FoundationPagination::Rails %>
<table>
  <thead>
    <th>Name</th>
    <th>From Date</th>
    <th>To Date</th>
    <th>Category</th>
    <th>Leave Type</th>
    <th>Actual Days</th>
    <th>Remaining Leaves</th>
    <th>Reason</th>
    <th>Status</th>
    <th colspan="2" width="37%">Actions</th>
  </thead>
  <tbody>
    <% attendances.each do |approval|%>
      <tr>
        <td><%= approval.user.name %></td>
        <td><%= date_format(approval.start_date) %></td>
        <td><%= date_format(approval.end_date) %></td>
        <td><%= approval.is_leave_or_wfh ? 'Leave' : 'Work From Home' %></td>
        <td>
          <%= approval.leave_type.name %>
        </td>
        <td><%= approval.actual_days %></td>
        <td>
          <%= approval.remaining_type_leaves %>
        </td>
        <td><%= approval.reason %></td>
        <td><%= attendance_current_status(approval) %></td>
        <td>
          <%= link_to('show', {controller: 'attendances', action: 'show', id: approval.id}, class: "button secondary tiny")%>
        </td>
        <td id="approval<%= approval.id%>">
          <%= form_tag approve_dashboard_index_path , :class => "approval_comments", :data => {:approvalid => approval.id, :needtoaddnotifiers=>approval.email_notification_getters.blank?} do %>
              <div class="field">
                <%= text_area_tag :comments, "", :placeholder => "Comments",:cols=>25, :rows=>5, :style => "resize: none;" %>
              </div>
              <%= hidden_field_tag("approval_id",approval.id) %>

              <ul class="button-group">
                <li><%= submit_tag 'Approve', class: 'button tiny', data: {confirm: 'Are you sure you wanna approve this!', btn: 'approve'} %></li>
                <li><%= submit_tag 'Reject', class: 'button tiny', data: {confirm: 'Are you sure you wanna reject this!', btn: 'reject'} %></li>
                <li><%= submit_tag 'Comment', class: 'button tiny', data: {btn: 'comment'} %></li>
              </ul>
              <input type="hidden" name="commit_action" value=""/>
          <% end %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate attendances, renderer: FoundationPagination::Rails %>

<div id="notification_recipient_modal" class="reveal-modal" data-reveal aria-labelledby="modalTitle">
  <h5 id="modalTitle">Add Recipients for notification of this leaves/wfhs approval</h5>
  <p>
    <%= select_tag :attendance_emails_to_notify, {}, {:multiple => true} %>
  </p>
  <p>
    <a href="javascript: void(0);" id="modal-approve-leave" class="button">Approve without adding Recipients</a>
  </p>
</div>

app/views/dashboard/_my_requests_show.html.erb
<table>
  <tr>
    <th>
      From Date
    </th>
    <th>
      To Date
    </th>
    <th>
      Leave Type
    </th>
    <th>
      Days
    </th>
    <th>
      Reason
    </th>
    <th>
      Status
    </th>
    <th>
      Actions
    </th>
  </tr>
  <% attendances.each do |approval|%>
      <tr>
        <td>
          <%= date_format(approval.start_date) %>
        </td>
        <td>
          <%= date_format(approval.end_date) %>
        </td>
        <td>
          <%= approval.is_leave_or_wfh ? 'Leave' : 'Work From Home' %>
        </td>
        <td>
          <%= approval.days %>
        </td>
        <td>
          <%= approval.reason %>
        </td>
        <td>
          <%= attendance_current_status(approval) %>
        </td>

        <td>

          <%= link_to("show", {:controller => 'attendances', :action => 'show', :id => approval.id}, :class => "actions") %>
          <% if (attendance_current_status(approval).equal?(:pending)) %>
              <%= link_to("edit", edit_attendance_path(approval.id), :class => "actions") %>
              <%= link_to("delete", {:controller => 'attendances', :action => 'destroy', :id => approval.id}, :method => :delete, :class => "actions") %>
          <% end %>
          <% if (attendance_current_status(approval).equal?(:rejected)) %>
              <%= link_to("resubmit", new_attendance_path(old_id: approval.id), :class => "actions") %>
          <% end %>

        </td>


      </tr>
  <% end %>

</table>

<script>
    $(document).ready(function() {
        click_approval();
    })
</script>

app/views/dashboard/_search_show.html.erb
<b>Approved Leaves</b> :
<b><%=@name%></b> has taken
<b><%= @sick %> sick</b> leaves,
<b><%= @casual %> casual</b> leaves and
<b><%= @privilege %> privilege</b> leaves



<table>
  <thead>
    <th>Name</th>
    <th>From Date</th>
    <th>To Date</th>
    <th>Leave Category</th>
    <th>Days</th>
    <th>Leave Type</th>
    <th>Reason</th>
    <th>Status</th>
  </thead>
  <tbody>
    <% attendances.each do |approval| %>
      <tr>
        <td><%= approval.user.name %></td>
        <td><%= date_format(approval.start_date) %></td>
        <td><%= date_format(approval.end_date) %></td>
        <td><%= approval.is_leave_or_wfh ? 'Leave' : 'Work From Home' %></td>
        <td><%= approval.days %></td>
        <td><%= approval.leave_type.name %></td>
        <td><%= approval.reason %></td>
        <td><%= attendance_current_status(approval) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/dashboard/_team_member_info.html.erb
<%= will_paginate my_team, renderer: FoundationPagination::Rails %>
<table width="100%">
  <thead>
    <th>Member Name</th>
    <th>Email</th>
    <td>
      <table border="0">
        <tr><td>Remaining</td></tr>
        <tr><td>Sick</td><td>Casual</td><td>Privilege</td></tr>
      </table>
    </td>
    <th>Leaves Taken</th>
    <th>Work From Home Taken</th>
    <th>Leaves Remaining</th>
  </thead>
  <tbody>
    <% my_team.each do |member| %>
      <tr>
        <td><%=member.name%></td>
        <td><%=member.email%></td>
        <td>
          <table border="0" width="100%">
            <tr><td style="text-align: center;"><%= member.sick %></td><td style="text-align: center;"><%= member.casual %></td><td style="text-align: center;"><%= member.privilege %></td></tr>
          </table>
        </td>
        <% leaves = member.attendances.where(:is_leave_or_wfh => true).where(:approval_status => true).sum(:days) %>
        <td><%= leaves %></td>
        <td><%= member.attendances.where(:is_leave_or_wfh => false).where(:approval_status => true).sum(:days) %></td>
        <% leaves_applicable =  member.sick.to_f + member.casual.to_f + member.privilege.to_f %>
        <td><%= leaves_applicable.round(2) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate my_team, renderer: FoundationPagination::Rails %>

app/views/dashboard/approve.js.erb
$(document).ready(function() {
        $(".approval_comments").bind("ajax:success", function () {
            $(this).parent().parent().remove();
           $('#see_requests')
                   .html("<%= escape_javascript(render(:partial => 'attendance_show',
                    :locals => {:attendances => current_user.approvals.where(approval_status: nil)})) %>");
            $('#member_info')
                    .html("<%= j(render(:partial => 'team_member_info' )) %>");
        });
})

app/views/dashboard/entire_team.html.erb
<%= will_paginate @entire_team, renderer: FoundationPagination::Rails %>
<table width="100%">
  <thead>
    <tr>
      <th width="20%">Name</th>
        Member Name
      </th>
      <th>
        Email
      </th>
      <th>
        Remaining Sick
      </th>
      <th>
        Remaining Casual
      </th>
      <th>
        Remaining Privilege
      </th>
      <th>
        Manager
      </th>
      <th>
        Leaves Taken
      </th>
      <th>
        Work From Home Taken
      </th>
    </tr>
  </thead>
  <tbody>
    <% @entire_team.each do |team_member| %>
      <tr>
        <td>
          <%= team_member.name %>
        </td>
        <td>
          <%= team_member.email %>
        </td>
        <td>
          <%= team_member.sick %>
        </td>
        <td>
          <%= team_member.casual %>
        </td>
        <td>
          <%= team_member.privilege %>
        </td>
        <td>
          <% if team_member.manager_id.nil? %>
            --
          <% elsif team_member.manager == current_user %>
            (You)
          <% else %>
            <%= team_member.manager.name %>
          <% end %>
        </td>
        <td>
          <% month_leaves = team_member.leaves_for_month(Date.today.month, Date.today.year) %>
          <% month_leaves.each do |leave| %>
            <div><%= leave %></div>
          <% end %>
          <div><b>Total:</b> <%= month_leaves.count %></div>
        </td>
        <td>
          <% month_wfhs =  team_member.wfh_for_month(Date.today.month, Date.today.year) %>
          <% month_wfhs.each do |wfh| %>
            <div><%= wfh %></div>
          <% end %>
          <div><b>Total:</b> <%= month_wfhs.count %></div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @entire_team, renderer: FoundationPagination::Rails %>

app/views/dashboard/index.html.erb
<br><br>
<div class="row">
  <% if is_admin %>
    <ul class="stack-for-small round secondary button-group">
      <li><%= link_to "Manage Roles", {:controller => 'roles'}, :class => 'secondary button small' %></li>
      <li><%= link_to "Show All Users", users_path, :class => 'secondary button small' %></li>
    </ul>
  <% end %>
  <br>

  <div class="row">
    <div class="large-3 columns">&nbsp;&nbsp;&nbsp;</div>
    <div class="large-6 columns">
      <ul class="stack button-group">
        <li>&nbsp;</li>
        <li><%= link_to "View Available Leaves", available_leaves_attendances_path, :class => "button" %></li>
        <li>&nbsp;</li>
        <li><%= link_to "View My Leave Requests", my_requests_attendances_path, :class => "button" %></li>
        <li>&nbsp;</li>
        <li><%= link_to "Submit New Request", apply_leave_attendances_path, :class => "button" %></li>

        <% if current_user.is_manager? || current_user.is_admin? %>
          <li>&nbsp;</li>
          <li><%= link_to "Pending Approvals", pending_approvals_attendances_path, :class => "button" %></li>
          <li>&nbsp;</li>
          <li><%= link_to "My Team Members", my_team_dashboard_index_path, :class => "button" %></li>
        <% end %>

        <% if current_user.is_admin? %>
          <li>&nbsp;</li>
          <li><%= link_to "Create new user", new_user_path, :class => "button" %></li>
          <li>&nbsp;</li>
          <li><%= link_to "Holidays", holidays_path, :class => "button" %></li>
        <% end %>

        <% if current_user.is_admin? ||  current_user.is_manager? %>
          <li>&nbsp;</li>
          <li><%= link_to "Search Leave Request", search_pending_approvals_attendances_path, :class => "button" %></li>
          <li>&nbsp;</li>
          <li><%= link_to "Entire Team", entire_team_dashboard_index_path, :class => "button" %></li>
        <%end%>
      </ul>
    </div>
    <div class="large-3 columns"></div>
  </div>


</div>



<!-- <div class="clear" style="clear:both"></div> -->



<script>
    $(document).ready(function () {
        attach_Click_event();
    })
</script>

app/views/dashboard/my_team.html.erb
<%= render(:partial => 'team_member_info', locals: {:my_team => @my_team}) %>

app/views/dashboard/search.js.erb
/**
 * Created by tt on 1/9/15.
 */

$(document).ready(function() {
    <% if !@user_attendances.blank? %>
    <% name = @user_attendances.first.user.name%>
   $('#search_results_count').html("<b><%= @user_attendances.count%> results found</b>")
   $('#search_results').html("<%= escape_javascript(render(:partial => 'search_show', :locals=>{:attendances => @user_attendances, :wfh => @work_from_home, :leaves_total => @total_leaves})) %>");
   $('#search_results').html("<%= escape_javascript(render(partial: 'dashboard/attendance_show', locals: {attendances: @user_attendances}))%>")
    <%else%>
    $('#search_results').html("No Results Found.");
    <%end%>
})

app/views/dashboard/search_my_requests.js.erb
/**
 * Created by tt on 1/9/15.
 */

$(document).ready(function() {
    <% if !@user_attendances.nil? & !@user_attendances.empty?%>
    <% name = @user_attendances.first.user.name%>
   $('#search_results').html("<%= escape_javascript(render(:partial => 'my_requests_show', :locals=>{:attendances => @user_attendances})) %>");
    $('#search_results_count').html("<b><%= @user_attendances.count%> results found</b>")
    <%else%>
    $('#search_results').html("No Results Found.");
    <%end%>
})