config/routes.rb
EmployeeManagement::Application.routes.draw do

  get "holidays/index"

  get "holidays/new"

  get "holidays/edit"

  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration, only: [:edit, :update], path: 'users', controller: 'devise/registrations', as: :user_registration
  end

  root :to => 'dashboard#index'
  resources :roles
  resources :attendances do
    collection do
      get :my_requests
      get :apply_leave
      get :pending_approvals
      get :search_pending_approvals
      get :available_leaves
      get :team_leaves
    end
  end
  post "dashboard/search" => "dashboard#search", :as => :dashboard_search
  resources :dashboard do
    collection do
      get :my_team
      get :approve
      get :entire_team
    end
  end

  resources :users

  resources :holidays

  match ':controller(/:action(:/id))'

  get 'search/search_emails' => 'search#search_emails'
  get 'search/search_name' => 'search#search_name'
  get 'search/search_manager_name' => 'search#search_manager_name'

end

app/models/holiday.rb
class Holiday < ActiveRecord::Base


  def self.leave_dates_for_year(year)
    holidays = Holiday.where("YEAR(on_date)='#{year}'")
    leave_dates = []
    holidays.each do |holiday|
      leave_dates << holiday.on_date.upto(holiday.on_date + (holiday.days - 1).days).map{|dt| dt}
    end
    leave_dates.flatten
  end

  # day here must be of a date class instance
  def self.is_in_between_holiday?(day)
    return Holiday.leave_dates_for_year(Date.today.year).include?(day)
  end
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_filter :check_admin, except: :index

  def index
    @holidays = Holiday.all
  end

  def new
    @holiday = Holiday.new
  end

  def create
    @holiday = Holiday.new(params[:holiday])
    respond_to do |format|
      if @holiday.save
        format.html { redirect_to holidays_path }
        format.json { render json: @holiday, status: :created, location: @holiday }
      else
        format.html { render action: "new" }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @holiday = Holiday.find(params[:id])
  end

  def update
    @holiday = Holiday.find(params[:id])
    respond_to do |format|
      if @holiday.update_attributes(params[:holiday])
        format.html { redirect_to holidays_path, notice: 'holiday was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @holiday = Holiday.delete(params[:id])
    redirect_to holidays_path, notice: 'holiday was successfully removed'
  end

  private

  def check_admin
    if !current_user.is_admin?
      redirect_to root_url
    end
  end
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/views/holidays/_form.html.erb
<%= form_for(@holiday) do |f| %>
  <% if @holiday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@holiday.errors.count, "error") %> prohibited this holiday from being saved:</h2>

      <ul>
      <% @holiday.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :on_date %><br />
    <%= f.date_select :on_date %>
  </div>
  <div class="field">
    <%= f.label :days %><br />
    <%= f.number_field :days, :class => 'text_field', :step => '1' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/holidays/edit.html.erb
<h1>Editing Holiday</h1>

<%= render 'form' %>

<%= link_to 'Show', @holiday %> |
<%= link_to 'Back', holidays_path %>

app/views/holidays/index.html.erb
<%#= back_to_home_button %>

<h2>Roles</h2>

<table>
  <thead>
    <th width="35%">Name</th>
    <th width="20%">Date</th>
    <th width="20%">Days</th>
    <th width="25%">Actions</th>
  </thead>
  <tbody>
    <% @holidays.each do |holiday| %>
      <tr>
        <td><%= holiday.name %></td>
        <td><%= holiday.on_date %></td>
        <td><%= holiday.days %></td>
        <td>
          <%= link_to 'Show', holiday, class: 'button tiny secondary' %>
          <%= link_to 'Edit', edit_holiday_path(holiday), class: 'button tiny secondary' %>
          <%= link_to 'Destroy', holiday, confirm: 'Are you sure?', remote: true, method: :delete , class: 'button tiny alert' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Holiday', new_holiday_path, class: 'button small' %>

app/views/holidays/new.html.erb
<h1>New Holiday</h1>

<%= render 'form' %>

<%= link_to 'Back', holidays_path %>