config/routes.rb
EmployeeManagement::Application.routes.draw do

  get "holidays/index"

  get "holidays/new"

  get "holidays/edit"

  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration, only: [:edit, :update], path: 'users', controller: 'devise/registrations', as: :user_registration
  end

  root :to => 'dashboard#index'
  resources :roles
  resources :attendances do
    collection do
      get :my_requests
      get :apply_leave
      get :pending_approvals
      get :search_pending_approvals
      get :available_leaves
      get :team_leaves
    end
  end
  post "dashboard/search" => "dashboard#search", :as => :dashboard_search
  resources :dashboard do
    collection do
      get :my_team
      get :approve
      get :entire_team
    end
  end

  resources :users

  resources :holidays

  match ':controller(/:action(:/id))'

  get 'search/search_emails' => 'search#search_emails'
  get 'search/search_name' => 'search#search_name'
  get 'search/search_manager_name' => 'search#search_manager_name'

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users

  # returns Role object for manager role
  def self.manager
    self.where(:name => "Manager").first
  end

  # returns Role object for admin role
  def self.admin
    self.where(:name => "admin").first
  end

  # returns Role object for developer role
  def self.developer
    self.where(:name => "Developer").first
  end


end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  include RolesHelper
  before_filter :is_admin!
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all

  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])
    if @role.save
      redirect_to :action => 'index', :notice => "role successfully created"
    else
      redirect_to :action => 'new'
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end

  def is_admin!

    if !(is_admin)
      redirect_to "/404.html"
    end
  end
end

app/helpers/roles_helper.rb
module RolesHelper

  def is_admin

    if current_user.roles.include?(Role.find_by_name(:admin))
      true
    else
      false
    end
  end
end

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :working_days %><br />
    <%= f.number_field :working_days %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :leaves_applicable %><br />
    <%= f.number_field :leaves_applicable, :class => 'text_field', :step => 'any' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<%#= back_to_home_button %>

<h2>Roles</h2>

<table>
  <thead>
    <th width="10%">Working days</th>
    <th width="20%">Name</th>
    <th width="30%">Leaves applicable</th>
    <th width="20%">Actions</th>

  </thead>
  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.working_days %></td>
        <td><%= role.name %></td>
        <td><%= role.leaves_applicable %></td>
        <td>
          <%= link_to 'Show', role, class: 'button tiny secondary' %>
          <%= link_to 'Edit', edit_role_path(role), class: 'button tiny secondary' %>
          <%= link_to 'Destroy', role, confirm: 'Are you sure?', method: :delete , class: 'button tiny alert' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Role', new_role_path, class: 'button small' %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Working days:</b>
  <%= @role.working_days %>
</p>

<p>
  <b>Name:</b>
  <%= @role.name %>
</p>

<p>
  <b>Leaves applicable:</b>
  <%= @role.leaves_applicable %>
</p>


<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>